services:
  - type: web
    name: disaster-management-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_SHEET_ID
        sync: false  # Set this in Render dashboard
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false  # Set this in Render dashboard
      - key: GOOGLE_PRIVATE_KEY
        sync: false  # Set this in Render dashboard
